version: '3.8'
services:
  backend:
    build: ./app
    ports:
      - "8000:8000"
    restart: always
    # Uncomment if you want to mount code for live reload in dev
    # volumes:
    #   - ./app:/app

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000
    depends_on:
      - backend
    restart: always
    # Uncomment if you want to mount code for live reload in dev
    # volumes:
    #   - ./frontend:/app
